// Generated by CoffeeScript 1.6.3
(function() {
  var Ivago;

  exports.Ivago = Ivago = (function() {
    function Ivago() {}

    Ivago.prototype.run = function() {
      var urls;
      urls = {
        calendar: "http://datatank.gent.be/MilieuEnNatuur/IVAGO-Inzamelkalender.json",
        streets: "http://datatank.gent.be/MilieuEnNatuur/IVAGO-Stratenlijst.json",
        appartments: "http://datatank.gent.be/MilieuEnNatuur/IVAGO-Appartementen.json"
      };
      return http.get(urls.appartments, function(res) {
        return console.log("GET " + urls.appartments, res.statusCode);
      }).on('error', function(error) {
        return console.error(e.message);
      });
    };

    return Ivago;

  })();

}).call(this);
